### ISSUE TITLE
How to make multi-tool workflows reproducible

### ISSUE THREAD

**Issue by naupaka** [NCEAS/open-science-codefest#15]
**Organizational Page**:  [MultiTool](https://github.com/NCEAS/open-science-codefest/wiki/MultiTool)
**Category**: Discussion
**Title**: How to make multi-tool workflows reproducible
**Proposed by**: Naupaka Zimmerman
**Participants**: 
**Summary**:

There are now some great tools to pull together description and analysis (IPython notebooks/Project Jupyter, knitr/Sweave in R, etc) when a project can work within a given language.  However, many projects (especially I am thinking of bioinformatics) leverage many different tools at different stages of data processing and analysis, each with their own versions, optional configuration parameters, etc.  It gets even tricker when part of the workflow is run on a server, cluster, or in the cloud, and other parts are done locally on the user's machine. How can such workflows be tracked and made transparent/reproducible? When working online through Galaxy, iPlant, etc, it can be possible to have a standardized pipeline that runs through the data from start to finish, but this is next to impossible for individuals to do locally, and often the standard pipelines can have issues if your data are not what the system is expecting.  

I was inspired several years ago when I read about [Phillip Guo's Burrito project](http://www.pgbovine.net/burrito.html) ([on Github](https://github.com/pgbovine/burrito)) and wonder if there isn't anything similar out there now to track what happens during exploratory data analyses and processing. A simple answer could be more widespread use of tools like `make`, but it would have to be something like `make` + a virtualenv + provenance tracking.  

I also hear very little among ecologists about workflow tools in general, and wonder if they could be of more use, or just overkill for what most individual ecologists do day-to-day: [VisTrails](http://www.vistrails.org/index.php/Main_Page), [Taverna](http://www.taverna.org.uk), [Kepler](https://kepler-project.org), etc. ([here's a review](http://ieeexplore.ieee.org/xpl/login.jsp?tp=&arnumber=4786077&url=http%3A%2F%2Fieeexplore.ieee.org%2Fxpls%2Fabs_all.jsp%3Farnumber%3D4786077) of six systems, from 2008).

**Comment by naupaka** [comment]
Closing as workshop is complete.

**Comment by chrismattmann** [comment]
haha nice @naupaka This may set the record for longest issue open ;) Thank you for closing!
